### ISSUE TITLE
Export jsonReferenceLoader or proper interface

### ISSUE THREAD

**Issue by h2non** [xeipuuv/gojsonschema#102]
Why you're not exporting it? If you don't want to export the struct directly, define an interface type for it.

**Comment by h2non** [comment]
Seems like `JSONLoader` is the exported interface. It would be better if you use it at function interface signature level to avoid doubts. 

Example:
```go
func NewReferenceLoader(source string) JSONLoader
```

**Comment by 0xdeafcafe** [comment]
+1 on this - would be very helpful.

**Comment by johandorland** [comment]
The function signature was changed to return `JSONLoader` with #202.
