### ISSUE TITLE
Validate structs

### ISSUE THREAD

**Issue by DaveBlooman** [xeipuuv/gojsonschema#118]
Im wondering if its possible to validate a struct and its tags.  In the readme it suggests you can do this, but im having difficulty using a custom struct.  In the example, there is the following, i've expanded it slightly, but it always comes back as a valid schema.

```go
package main

import (
	"fmt"

	"github.com/xeipuuv/gojsonschema"
)

type Root struct {
	Users []User `json:"users"`
}

type User struct {
	Name string `json:"name"`
}

func main() {

	test := `{"testing": "testing"}`

	data := Root{}
	data.Users = append(data.Users, User{"John"})

	loader := gojsonschema.NewGoLoader(data)
	testLoader := gojsonschema.NewStringLoader(test)

	result, _ := gojsonschema.Validate(loader, testLoader)

	fmt.Println(result.Valid())
	fmt.Println(result.Errors())

}
```

Is this the correct usage?

**Comment by xeipuuv** [comment]
You do not provide a valid schema.

**Comment by DaveBlooman** [comment]
The struct is the thing I'm trying to validate against, is that not valid here?

**Comment by xeipuuv** [comment]
http://json-schema.org/examples.html
