### ISSUE TITLE
custom locale bug

### ISSUE THREAD

**Issue by alioygur** [xeipuuv/gojsonschema#119]
Hello I think there is an error. with this line
https://github.com/xeipuuv/gojsonschema/blob/master/locales.go#L76

the httpBadStatus should be global.(CamelCase)

how can I use Custom locale? we cannot implement to that.

**Comment by ahmetalpbalkan** [comment]
You're right. There doesn't seem to be any implementations for this type on GitHub. https://sourcegraph.com/github.com/xeipuuv/gojsonschema@4f624f6197547606054e042e7903db103585e151/-/refs/GoPackage/github.com/xeipuuv/gojsonschema/-/locale

**Comment by ahmetalpbalkan** [comment]
I would suggest, just send a patch fixing that.

**Comment by sgumpalli** [comment]
https://github.com/xeipuuv/gojsonschema/pull/139

Fixed custom locale bug
