### ISSUE TITLE
Empty array is treated as null

### ISSUE THREAD

**Issue by dnephin** [xeipuuv/gojsonschema#141]
Example

```json
{"values": []}
```

would fail to validate with this schema:

```json
{
  "type": "object",
  "properties": {
    "values": {"type": "array"}
  }
}
```

I believe this is because
https://github.com/xeipuuv/gojsonschema/blob/ff0417f4272e480246b4507459b3f6ae721a87ac/validation.go#L93-L94 checks for nil before other types, but `[]interface{} == nil` evaluates to true.

I believe the above data should be valid against the schema.

**Comment by johandorland** [comment]
Actually your example validates fine. The problem has to do with the way the yaml docker compose file is parsed. If I look at how the yaml parser parses the ```ports: []``` part is turned into ```[]interface(nil)```, which is just ```nil```, not an empty array. Because in JSON there is a distinction between an empty array and nil/null it will fail to validate.

To fix this you can change the schema to allow for null, or you have to submit a PR to go-yaml so that it actually emits an empty array instead of nil when parsing an empty array.

```
{
  "type": "object",
  "properties": {
    "values": {"type": [ "array", "null" ]}
  }
}
```

```
type TestStruct struct {
	Values []int `json:"values"`
}

func TestEmptyArray(t *testing.T) {
	loader := NewStringLoader(`{
		"type": "object",
		"properties": {
			"values": {"type": "array"}
		}
		}`)

	schema, _ := NewSchema(loader)

	// Use a map to represent the JSON
	obj := make(map[string]interface{})

	// Validates correctly
	obj["values"] = make([]interface{}, 0)

	// Is invalid
	//obj["values"] = nil

	fmt.Println(strconv.FormatBool(obj["values"] == nil))

	var documentLoader JSONLoader = NewGoLoader(obj)

	// Validates correctly
	// documentLoader = NewGoLoader(TestStruct{Values: make([]int, 0)})

	// Is invalid, as Values is nil, not an empty array
	// documentLoader = NewGoLoader(TestStruct{Values: nil})

	// Validates correctly
	// documentLoader = NewStringLoader("{\"values\": []}")

        // Is invalid
        // documentLoader = NewStringLoader("{\"values\": null}")

	result, derr := schema.Validate(documentLoader)

	if derr != nil {
		t.Errorf("An error occured while validating: %s", derr.Error())
	}
	if !result.Valid() {
		t.Errorf("Unexpected errors: %s", result.Errors()[0].Description())
	}
}
```

**Comment by dnephin** [comment]
@johandorland Thanks for looking into it. I agree it could be fixed from go-yaml. I thought it might also be possible for `gojsonschema` to detect the difference with reflection, but maybe that's not the correct solution.

**Comment by johandorland** [comment]
It is technically possible to check whether the type of the ```nil``` value is ```[]interface{}```go, but it's only a workaround for your problem. ```gojsonschema``` doesn't feel like the the proper place for these type of exceptions and workarounds as it might very well cause unexpected behaviour for others..
