### ISSUE TITLE
NewReferenceLoader passing non-canonical reference

### ISSUE THREAD

**Issue by Deseao** [xeipuuv/gojsonschema#144]
Possibly related to [#104](https://github.com/xeipuuv/gojsonschema/issues/104), creating a schema from a reference loader throws the following error

`Reference {0xc4202e2e80 {[]} false true false false true} must be canonical`

My test:

```
func TestCustomSchemaByFile(t *testing.T) {
	path, err := filepath.Abs("./test.json")
	reader := NewReferenceLoader(path)
	_, err = NewSchema(reader)
	assert.Nil(t, err)
}
```
where the contents of test.json is
`{
    "type": "object"
}`

Note that

```
func TestCustomSchemaByString(t *testing.T) {
	path, err := filepath.Abs("./test.json")
	bytes, err := ioutil.ReadFile(path)
	reader := NewStringLoader(string(bytes))
	_, err = NewSchema(reader)
	assert.Nil(t, err)
}
```

passes.

**Comment by xeipuuv** [comment]
The URL scheme must start with "file://"
see https://github.com/xeipuuv/gojsonschema#loaders
