### ISSUE TITLE
Remove property-field from RequiredError Errordetails

### ISSUE THREAD

**Issue by KevinSjoberg** [xeipuuv/gojsonschema#155]
There is no need for `RequiredError` to have a `property` field in its `ErrorDetails` since we're always [setting the field property](https://github.com/xeipuuv/gojsonschema/blob/master/errors.go#L239).

Let's remove it.

Thoughts?

**Comment by KevinSjoberg** [comment]
Doing some issue cleanup on my side. Shall I close this?

**Comment by KevinSjoberg** [comment]
@johandorland could I close this?

**Comment by johandorland** [comment]
I haven't really looked into this. If you want to close this issue feel free to do so.
