### ISSUE TITLE
Add Draft-06 and Draft-07 support

### ISSUE THREAD

**Issue by johandorland** [xeipuuv/gojsonschema#178]
I've been looking at adding support for draft-06 and draft-07 recently. This should be very doable, but it seemed like at least a good idea to make a todo public list and maybe have a public discussion about some implementation details. Draft-06 introduces some backwards incompatible changes, most notably changes to `exclusiveMinimum`, `exclusiveMaximum`, `id` vs `$id` and the possibility to have a property named `$ref`.

- [x] The current test setup is a bit of a PITA to maintain (especially now with different draft versions), so it's probably best to ditch the current test suite and create one that directly uses the test files as defined in the official test suite without manual transformation like now. The current setup has the advantage however that errors are checked more thoroughly than just being valid or invalid however.
- [x] Add support for handling different versions of JSON Schema. Detection of the version could be done based on the `$schema` keyword. Default to draft-04 for backwards compatibility.
- [x] Add some new interfaces to different loaders so a specific draft be enforced upon schema loading time instead of relying on the `$schema` keyword. This would probably be needed for testing, but some developers might also want to manually enforce it.
- [x] Add support for `propertyNames`, `contains` and `const`
- [x] Change some behaviour related to edge cases (`requires`, `dependencies` and using booleans as schemas) I'd not be surprised if gojsonschema already handles some of these correctly by accident.
- [ ] A lot of new metadata fields are added like `examples`, `$comment`, `readOnly`, `writeOnly`, `contentMediaType`, `contentMediaEncoding`, etc. The current metadata fields like `title` and `description` are parsed, but nothing is done with the data. If we implement https://github.com/xeipuuv/gojsonschema/issues/174, there is really no need to even look at these type of fields explicitly since they are not used for validation.
- [x] Add a bunch off new format checkers. Both draft-06 and draft-07 defined a lot of them. It happens that `regex`, `date` and `time` were already part of draft-03 and also implemented here.
- [x] If-then-else is the biggest part of draft-07, but a pull request is already pending #177 

For anyone interested here are the release notes for [draft-06](http://json-schema.org/draft-06/json-schema-migration-faq.html) and [draft-07](http://json-schema.org/draft-07/json-schema-release-notes.html)

**Comment by handrews** [comment]
Note that the added emphasis on meta-data is likely to continue (but not necessarily all in the validation spec).  json-schema-org/json-schema-spec#530 tracks formalizing how that should work and will likely result in more formal guidance on annotations / metadata collection in draft-08.  You might want to keep that in mind while adding support now.

**Comment by ajackson-cpi** [comment]
Your top-level repo title says it only supports draft-04

**Comment by johandorland** [comment]
> Your top-level repo title says it only supports draft-04

I only have commit rights, so I can't edit the description. @xeipuuv, could you change the description for the repo to include draft v6 and dravt v7 support?
