### ISSUE TITLE
Validate() does not work with ReaderLoader

### ISSUE THREAD

**Issue by domano** [xeipuuv/gojsonschema#181]
Hi!

If i do something like this 
`func (h *myHandler) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
jsonLoader, newBody := gojsonschema.NewReaderLoader(r.Body)
res, err := vH.schema.Validate(jsonLoader)
...(and so on)
`

i get no results. This is because of the reader returning an io.EOF-error (which is to be expected and perfectly fine.)

I think this should work with EOF-errors.

**Comment by domano** [comment]
This fixes the problem
https://github.com/xeipuuv/gojsonschema/pull/182

**Comment by domano** [comment]
Ok, i am copying from the teeReader before doing the validation now and it works now.
Maybe a comment would be nice, so that people dont use the jsonLoader before reading the Reader

**Comment by johandorland** [comment]
The interface is a bit misleading as you'd expect it to read by itself instead of returning another reader which you then have to drain (although this approach is very useful if you also want to use the same Reader for getting the data yourself too) It's indeed probably not a bad idea to add this to the documentation as it even fooled me twice before I understood it :grin: Thanks for your input anyway.

**Comment by filipesilvaa** [comment]
this is a kind confusing, I got the same problem, reading comments here, this is the solution:
```

**Comment by filipesilvaa** [comment]
This is a little confusing, I got the same problem, reading comments here, this is the code:
```go
loader, copyReader := gojsonschema.NewReaderLoader(r.Body)
_, _ = ioutil.ReadAll(copyReader)

// or
// buf := new(bytes.Buffer)
// buf.ReadFrom(copyReader)

response, err := schema.Validate(loader)
...
```
Is it better to save this `NewReaderLoader` as `StringLoader` ?
Cause if you need to read the copy of reader (TeeReader), it's better to apply a NewStringLoader (or struct reference, etc) or not ? you can re-use this variable (if it's a struct/string) to do some other stuffs.

```go
b, _ = ioutil.ReadAll(r.Body)
body := string(b)

// or
// buf := new(bytes.Buffer)
// buf.ReadFrom(r.Body)
// body := buf.String()

loader := gojsonschema.NewStringLoader(body)
response, err := schema.Validate(loader)
...
```
