### ISSUE TITLE
enum is not nullable

### ISSUE THREAD

**Issue by ghigt** [xeipuuv/gojsonschema#184]
Enum should be nullable
```json
{
    "foo": null,
}
```
for:
```json
{
    "type": "object",
    "properties": {
        "foo": {
            "type": ["string", "null"],
            "enum": ["hello"]
        }
    }
}
```

**Comment by johandorland** [comment]
So this is how I read your schema.

- The type of property `foo` must be either `string` or be `null`
- According to the single array enum, property `foo` must be `"hello"`

While your example validates the type check, it does not validate the enum check. If you want `null` to be valid according to the enum, you should add it to the enum which gives you:
```json
{
    "type": "object",
    "properties": {
        "foo": {
            "type": ["string", "null"],
            "enum": ["hello", null ]
        }
    }
}
```

In most cases type checks on enums are redundant as the enum does basically the same thing already, but stricter.

**Comment by ghigt** [comment]
Thx 👍
