### ISSUE TITLE
The integer type doesn't validate Int64 properly

### ISSUE THREAD

**Issue by frol-kr** [xeipuuv/gojsonschema#192]
Validation of the integer type is incorrect for the number that are close to max int64 (i guess that this also happens for min int64).

The conversion was introduced in https://github.com/xeipuuv/gojsonschema/pull/100
Here is playground ex with incorrect conversion: https://play.golang.org/p/Ut53ulNt1Nh
Also, a link to source: https://github.com/xeipuuv/gojsonschema/blob/master/utils.go#L87
```golang
func checkJsonNumber(what interface{}) (isValidFloat64 bool, isValidInt64 bool, isValidInt32 bool) {

	jsonNumber := what.(json.Number)

	f64, errFloat64 := jsonNumber.Float64()
	s64 := strconv.FormatFloat(f64, 'f', -1, 64)
    	_, errInt64 := strconv.ParseInt(s64, 10, 64)

	isValidFloat64 = errFloat64 == nil
	isValidInt64 = errInt64 == nil

	_, errInt32 := strconv.ParseInt(s64, 10, 32)
	isValidInt32 = isValidInt64 && errInt32 == nil

	return
}
```

**Comment by johandorland** [comment]
You're right, it's buggy, but it shouldn't just work for up to 64 bit numbers. #172 was designed to remove rounding errors, but it also basically added big number support. The thing I missed there was to update parts of the code like this. The whole number handling needs an extra revision to remove all the old float64 and int64 stuff.
