### ISSUE TITLE
How to validate unexpected field with gojsonschema?

### ISSUE THREAD

**Issue by Houlton** [xeipuuv/gojsonschema#205]
This is my schema:
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
	"required": ["name"],
	"properties": {
		"name": {
			"type": "string"
		}
         }
}

And this is my json content:
{
    "name" : "tony",
    "age" : 20
}

Field "age" is not in schema, but Validate OK.

**Comment by Houlton** [comment]
Hi,
Anyone answer my question?

**Comment by handrews** [comment]
@Houlton you may be interested in the [JSON Schema slack](https://join.slack.com/t/json-schema/shared_invite/enQtMjk1NDcyNDI2NTAwLTcyYmYwMjdmMmUxNzZjYzIxNGU2YjdkNzdlOGZiNjIwNDI2M2Y3NmRkYjA4YmMwODMwYjgyOTFlNWZjZjAyNjg), which is a better forum for general questions on how to use JSON Schema.

For your current question, you probably want to `"additionalProperties": false`

**Comment by Houlton** [comment]
@handrews  Thanks for your advice, it works well.
