### ISSUE TITLE
windows file path is not handled correctly

### ISSUE THREAD

**Issue by zhlicen** [xeipuuv/gojsonschema#209]
**example**:
```
schemaLoader := gojsonschema.NewReferenceLoader("file://d:/schema/schema.json")
....
....
[Error]
open schema/sehcma.json: The system cannot find the path specified
```

**cause**:
url parsed the drive letter "d:" as the _Host_, and the path "schema/schema.json" as the _Path_,
in the code below, it only takes the ```refToUrl.GetUrl().Path```("schema/schema.json") as the file path, which cause the open file error.
```
https://github.com/xeipuuv/gojsonschema/blob/b84684d0e066369f2a7a8a525f3080909ed4ea6b/jsonLoader.go#L141
```

**Comment by johandorland** [comment]
The rather trivial fix seems to be to just use the entire URI instead of just the Path component. I'll try to merge a fix in the near future.

**Comment by zhlicen** [comment]
hi @johandorland ,thanks!
