### ISSUE TITLE
Repeated attributes not highlighted as errors

### ISSUE THREAD

**Issue by Matias-Barrios** [xeipuuv/gojsonschema#211]
So, I am having this issue, I see that when certain attribute appears two times, the library is not throwing any kind of error for it. For instance, If I validate something like this : 

![image](https://user-images.githubusercontent.com/30472800/43905485-ccffc356-9bb6-11e8-862a-f02568072a49.png)

I dont get any kind of error. I was expecting to have something like "Additional property not allowed". Has someone faced the same issue I am now?

**Comment by johandorland** [comment]
This is a duplicate of #78. In short, the behaviour of duplicate fields is left undefined by the JSON specification and is not supported by the Go standard library and therefore also not by gojsonschema.

**Comment by Matias-Barrios** [comment]
@johandorland Got you then. 👍
