### ISSUE TITLE
Consider making names shorter

### ISSUE THREAD

**Issue by maxhawkins** [xeipuuv/gojsonschema#24]
Names in Go are [usually short](http://golang.org/doc/effective_go.html#names).

Shorter type and package names are more idiomatic and less to type. For example:

gojsonschema -> jsonschema
GetFileJson -> GetFile
GetHttpJson -> GetHTTP ([initialism](https://code.google.com/p/go-wiki/wiki/CodeReviewComments#Initialisms))
JsonSchemaDocument -> Document
ValidationResult -> Result

**Comment by xeipuuv** [comment]
I considered these enhancements for the lastest update, thanks.
