### ISSUE TITLE
Non zero  required error even if JSON string complies to schema

### ISSUE THREAD

**Issue by caveman7** [xeipuuv/gojsonschema#250]
I faced `non zero value required` even if the JSON string complies to schema:

My json string: 

```
{\"saltedHash\":\"a524e855ab5ae62e6906460fca53c40b099790398427ca0801487991e933534868a506e127c97322c9c7240834742339e133c93873d66092bb563caf9fe66720\",\"salt\":\"72fc0c3292ec5770\",\"kycScore\":0}
```

My schema:
```
{
    "definitions": {},
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://example.com/root.json",
    "type": "object",
    "title": "The Root Schema",
    "required": [
        "saltedHash",
        "salt",
        "kycScore"
    ],
    "properties": {
        "saltedHash": {
            "$id": "#/properties/saltedHash",
            "type": "string",
            "title": "The Saltedhash Schema",
            "default": "",
            "examples": [
                "24d98018b30ded802dc2790156b39d21a0074fd4ba9f0621c7a39ca0d6b1f98aac46e368e4682085b18352e1f14612967e62ba4231a0f144927ec0cb1acf1c09"
            ],
            "pattern": "^(.*)$"
        },
        "salt": {
            "$id": "#/properties/salt",
            "type": "string",
            "title": "The Salt Schema",
            "default": "",
            "examples": [
                "f368f87547069316"
            ],
            "pattern": "^(.*)$"
        },
        "kycScore": {
            "$id": "#/properties/kycScore",
            "type": "integer",
            "title": "The Kycscore Schema",
            "default": 0,
            "examples": [
                100
            ],
            "minimum": 0,
            "maximum": 1000
        }
    }
}
```

**Comment by rhugga** [comment]
I'm seeing a similar issue trying to validate kubernetes objects against their JSON specs. Never pulled my hair out more, or dug in like a tick into an issue in my near 20 years career. I can't get over how much a PITA doing this is in kubernetes land. We have a CRD that embeds a basic core v1 PodSpec. I have a dereferenced JSON schema for the PodSpec. (https://github.com/garethr/kubernetes-json-schema/blob/master/v1.13.1-standalone/podspec.json)

I can't for the life of me get a successful validate. Specs that work fine, get accepted by kubectl (which operates in strict mode too boot) do not pass validation.

Let me know if you have any luck. I'm beyond frustrated on this. Code that should have taken me 1 hour to write and vet has now sucked up 2 entire weeks and over 120 hours of my time. I've tried repo after repo, approach after approach. I'm about to go brute force on this and write all my own libraries from the ground tailored specifically for kubernetes. Man passing data between C++ application before the days of XML was easier than this.

**Comment by johandorland** [comment]
Your example validates as expected for me. The error you described also doesn't seem to be one generated by `gojsonschema`.  If I google the error I can find https://github.com/asaskevich/govalidator/issues/140, which seems to treat 0 as an invalid number, but I fail to see the connection to `gojsonschema` at this moment.

**Comment by aldredb** [comment]
@johandorland yes sorry about that. I checked again and it is false alarm. it is due to `govalidator` not this package. please close this issue

**Comment by caveman7** [comment]
@johandorland I checked again and you're right, the error is not caused by this package but by `govalidator`. Apologies for the false alarm.
