### ISSUE TITLE
Anyone wanna make $500 US quick and easy? No joke.

### ISSUE THREAD

**Issue by rhugga** [xeipuuv/gojsonschema#251]
Help me get validation working with a Kubernetes 1.13.1 v1 PodSpec. I've pulled my hair out and burned 120 hours across 2 weeks trying every approach under the sun and countless repos all claiming they can do this.

I have a dereferenced v1 PodSpec JSON object. 

I get a struct from kubernetes (core v1 PodSpec). 

I need to validate the spec conforms to the JSON object. 

Why is this so hard in kubernetes land? I've tried marshalling/unmarshalling using JSON and YAML. Neither approach work. To make matters worse, the kubernetes community as a whole is fragmented and there really is no central place to collaborate. Github is absolutely terrible for this. They've abandoned using slack, although their slack channel was never useful anyways for anything other than simple setup questions. Hell I even liaised with some former googlers who worked with Borg, the predecessor to Kubernetes and they weren't any help.

If someone knows how to do this, I will pay you $500 US for 1 hour of your time. Probably not even that long. I'm dead serious. Paying someone $500 is far more prudent than burning another 2 weeks on this issue. We can find a way to arrange payment so that neither of us needs to worry about getting ripped off. 

Never wanted to put an issue to bed as badly as I do this. My god what a headache.

**Comment by johandorland** [comment]
Do you have a code sample you expect to work but doesn't? From your description it's kind of hard to figure out what is going on and I have no experience with Kubernetes. It's quite possible some things get lost in translation somewhere with all the YAML/Go structs/JSON conversions. I've seen related things getting reported here before.

In case you need someone to vent to in a chatroom you can find me in the [JSON schema slack](https://join.slack.com/t/json-schema/shared_invite/enQtNjc5NTk0MzkzODg5LTVlZGIxNmVhMGY2MWFlYTdiNDQ5NWFiZGUwOThhNmYxZDE0YzA5YjRiOTA5MGY4ZTZlZGZhZDFmYTY4NWM2N2Y)

**Comment by rhugga** [comment]
I'll post it after I'm done trying my latest approach. It's gotta be something simple I'm missing in the midst of my lack-of-sleep super. Either that or there is some deep-rooted issue with kubernetes 1.13.1.
