### ISSUE TITLE
Add go.mod

### ISSUE THREAD

**Issue by Ferix9288** [xeipuuv/gojsonschema#259]
Is there any particular reason why there's no `go mod`?

Major benefit is storing dependency versions. If there's ever an API contract change, this package won't be affected by it.

**Comment by johandorland** [comment]
Because `go mod` is new (from this library's perspective) and nobody has bothered to send a PR yet. It's definitely something that should probably be added, given it's popularity, but I haven't come around to looking at how it works (I don't really do other Go stuff besides this lib atm).

**Comment by Ferix9288** [comment]
Hi Johan, appreciate the response back! Ah, I can make a simple PR for that. It's really not too bad.
