### ISSUE TITLE
Incomplete context when validating additionalProperties 

### ISSUE THREAD

**Issue by mabn** [xeipuuv/gojsonschema#266]
When additionalProperties is defined as:
```json
"additionalProperties": {
    "type": "string"
}
``` 

and the validation of such property fails, the property name is not included in the error context.

For example I want validation of this document:
```json
{
  "Device": {
    "Color": true
  }
}
```

To fail with an error message:
```
Device.Color: Invalid type. Expected: string, given: boolean
```
but instead the message is:
```
Device: Invalid type. Expected: string, given: boolean
```

With multiple keys under Device it is hard to understand what part of the document is incorrect.

The problematic schema:
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "Device": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    }
  }
}
```

When using `patternProperties` instead of `additionalProperties` then the error message is correct.

**Comment by mabn** [comment]
From what I understand the issue is in validation.go:672 there's a call:
```
validationResult := additionalPropertiesSchema.subValidateWithContext(value[pk], context)
```

which should instead get as a second parameter `subContext := NewJsonContext(pk, context)`

Here's a test for this issue:
<details><summary>CLICK ME</summary>
<p>



```go
func TestAdditionalPropertiesErrorMessage(t *testing.T) {
	schema := `{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "Device": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    }
  }
}`
	text := `{
		"Device":{
			"Color" : true
		}
	}`
	loader := NewBytesLoader([]byte(schema))
	result, err := Validate(loader, NewBytesLoader([]byte(text)))
	if err != nil {
		t.Fatal(err)
	}

	if len(result.Errors()) != 1 {
		t.Fatal("Expected 1 error but got", len(result.Errors()))
	}

	expected := "Device.Color: Invalid type. Expected: string, given: boolean"
	actual := result.Errors()[0].String()
	if actual != expected {
		t.Fatalf("Expected '%s' but got '%s'", expected, actual)
	}
}
```

</p>
</details>

I can create a PR if you prefer that but I don't see a good place where I could add a test for an error message.

**Comment by johandorland** [comment]
I was working on this part of the code doing some refactoring. I'll include a fix for this and merge the fix today or tomorrow.
