### ISSUE TITLE
Please consider receiving a string with the schema in gojsonschema.NewJsonSchemaDocument

### ISSUE THREAD

**Issue by c4milo** [xeipuuv/gojsonschema#28]
gojsonschema is a library, getting the schema or JSON data content is sometimes handled by the programs using the library thus making `gojsonschema.NewJsonSchemaDocument` unfriendly for those cases.

**Comment by xeipuuv** [comment]
JSON Strings are now allowed as arguments.

**Comment by c4milo** [comment]
:dancers: thank you!
