### ISSUE TITLE
Support custom types in the schema

### ISSUE THREAD

**Issue by georgysavva** [xeipuuv/gojsonschema#282]
Hi. Since we can validate a Go struct or a map with the jsonschema library. I am wondering is it possible to specify custom types in the schema e.g. `time.Time` or `url.URL`. Like it's done in the python version of the json schema: [here](https://python-jsonschema.readthedocs.io/en/stable/validate/#validating-with-additional-types)
I couldn't find any information about is it feature supported or maybe it will be in the future. Thank!

**Comment by johandorland** [comment]
`gojsonschema` is designed to work on JSON and validates structs by converting them to JSON first. Apparently the python library works a bit differently internally which makes it possible.
If you want this kind of functionality you're probably better off with a Golang specific validator library

**Comment by georgysavva** [comment]
Got it. Thanks for the explanation.
