### ISSUE TITLE
Loading schema from a in-memory cache

### ISSUE THREAD

**Issue by veeral-patel** [xeipuuv/gojsonschema#286]
Hi! Thanks for this library!

My code looks something like this:

```
// Load the schema and the config data to validate
schemaLoader := gojsonschema.NewReferenceLoader("file://schemas/my_config.json")
documentLoader := gojsonschema.NewGoLoader(myStruct)
```

Notie that I'm loading my JSON schema from disk every time I run this code.\

Instead, I'd like to somehow load from disk once and then cache it there so subsequent calls access the JSON schema in memory.

How would I achieve this?

**Comment by isupovs** [comment]
@veeral-patel How did you manage this issue? Is there a way to solve it?
