### ISSUE TITLE
Caching?

### ISSUE THREAD

**Issue by ianaz** [xeipuuv/gojsonschema#301]
Hi @xeipuuv , thanks for the work!
I was wondering if there's some caching for HTTP schemas as with our unit test, we hit the mocked http server twice when validating (twice). Is there an header we should set for it?
We tried with `Cache-Control: max-age=604800` but still hitting twice

Thank you

**Comment by johandorland** [comment]
Do you reuse schema instances with `schema, err := gojsonschema.NewSchema(schemaLoader)` or do you use `gojsonschema.Validate(schemaLoader, documentLoader)`?

**Comment by ianaz** [comment]
I'm using `gojsonschema.Validate(...)` like this:
```
	schemaStructureLoader := gojsonschema.NewReferenceLoader(schemaURL)
	schemaLoader := gojsonschema.NewGoLoader(schemaRepresentation)
	result, err := gojsonschema.Validate(schemaStructureLoader, schemaLoader)
```

Okay, then I guess I should use NewSchema(..) and reuse that one, got it, thanks :)
