### ISSUE TITLE
must be canonical - Windows Relative Path for sub schema

### ISSUE THREAD

**Issue by vguhesan** [xeipuuv/gojsonschema#320]
Hello:
I have the following files under "C:/path/to/your/schema/" folder (under Windows):
```
    schema.json
    a.json
    b.json
```

Within schema.json, I have two refs:
```
    "$ref": "file://a.json"
    "$ref": "file://b.json"

```
And $id in schema.json is defined as below:
   ` "$id": "schema.json"`

I load the main schema file like this:
  `schemaLoader := gojsonschema.NewReferenceLoader("file:///C:/path/to/your/schema/schema.json")`

My expectation is that when it see the $ref, it will load the sub-schema's using the relative path.

I get the following error:
  `Reference file://a.json#definitions/address must be canonical.`

I have tried various combinations for the $ref's such as `"a.json"`, `"file:///a.json"`, etc. 

I don't want to convert each file's $ref to an absolute path.

Anyway to address this so that the relative documents will be fetched?

**Comment by singhsidak54** [comment]
hey, were you able to resolve this issue?

**Comment by vguhesan** [comment]
> hey, were you able to resolve this issue?

When you do something like this, then it works:

```

"properties": {
  "address": {"$ref": "a.json#/definitions/address"}
}

```
