### ISSUE TITLE
Volunteering to maintain

### ISSUE THREAD

**Issue by mattwelke** [xeipuuv/gojsonschema#347]
Hi, we've been using this library in production for about 7 months now, with no plans to stop using it. In fact, we're using it more and more. I see a lot of open PRs and issues, and I've also seen a few people step up to volunteer to maintain it. I'd like to volunteer myself. I'm going to ping the others I've seen volunteer too to see if they're still interested. I suggest we use this issue to centralize discussion about maintainership.

@xeipuuv Are you open to adding people as maintainers?

**Comment by mattwelke** [comment]
People I've noticed volunteer to maintain in the past:

* @anandsunderraman
* @lpessoa
* @johandorland (didn't see a message from you explicitly stating this, but I've noticed you discuss having "to do lists" and I've seen you fork this library and have commits here)

**Comment by piotrszyma** [comment]
My organisation also started using that on prod with success, so if you'll need any more help I'm also happy to discuss / contribute ;)

**Comment by pierrecamilleri** [comment]
Same here, we would like to use it in prod and we would be willing to (modestly) contribute.

**Comment by Surfoo** [comment]
I don't think you can't count on this repository to maintain it, and a fork should be created..

**Comment by mattfarina** [comment]
This project is a dependency of a bunch of other open source projects so it would be good for it to be maintained.

I've reached out (via email) to the maintainer and have not yet gotten a response.

If there is to be a folk, I would hope a single folk can be created that the larger projects are willing to use.

**Comment by piotrszyma** [comment]
Hmm if the maintainer no longer wants to contribute then either one of us can create a fork or we can create a separate organisation? WDYT?

**Comment by anandsunderraman** [comment]
Or should we reach out to github support to see if they can hand over the rights to maintain this repo to the set of folks willing to maintain it.

**Comment by mattwelke** [comment]
I'm going to take my hat out of the ring. Things got busy, and it's clear there are plenty of others who also want to maintain.

As far as I know, in the open source community, a fork is most appropriate when the original maintainer isn't available. It might seem a bit hostile to ask GitHub to hand over a repo someone else created.

**Comment by TRiggAtGM** [comment]
I think it would be best to set up an organization and to create a fork there. I think it seems evident that the owner of this repository has no intention of resuming support for it themself as they have not been active on GitHub in over two years (probably got busy, as this is the constant risk of the open source world). I'm a neophyte to this space so I don't feel comfortable taking on those initial steps to start, but I do think it's just going to take someone saying "Okay, it's time someone did the thing"

**Comment by decentralgabe** [comment]
also in favor of seeing this maintained. is there a fork yet?

**Comment by Surfoo** [comment]
Hello there :wave:

ok, nobody created a fork of this projet, so I just forked it within a new organization: https://github.com/gojsonschema/gojsonschema.
Let me know here if you want contribute to this fork, and I'll add you as member/whatever. The rest will happen there now.

**Comment by mattwelke** [comment]
I agree with the decision to fork to a new org of the same name. I think we've given the creator plenty of time to chime in. It is important that the library is taken into a good direction, community-maintained, for the future. Given that we haven't heard back from @xeipuuv for a while, I hope they're doing okay.

To clarify, at this time, I'm not requesting to be added as maintainer to the new fork.

**Comment by danielloader** [comment]
@Surfoo assuming you're still involved, can you enable issues (and or discussions) on the forked repositories?
