### ISSUE TITLE
Custom keywords

### ISSUE THREAD

**Issue by prettymuchbryce** [xeipuuv/gojsonschema#50]
What do you think about allowing for the definition of new keywords with custom behavior ?

In other words, allowing for projects utilizing gojsonschema to define their own schema properties on top of those standard to the json-schema v4 spec.

It seems like a useful feature which would allow for some nice extendability. 

There is a javascript json-schema library called [tv4](https://github.com/geraintluff/tv4#definekeywordkeyword-validationfunction) which supports similar functionality.

**Comment by xeipuuv** [comment]
I don't have any specific use in mind for it right now but this is still an interesting idea.

**Comment by prettymuchbryce** [comment]
My use involves defining keywords for custom validation. For instance, I could define a new keyword called isPalindrome, which would validate that the field was a palindrome. This is convenient when you want all of the existing benefits of json schema, but want to be able to extend it with your own keywords and validations.

I have created the change on my fork. If there is any interest I could submit a PR.

https://github.com/prettymuchbryce/gojsonschema/commit/c02b0555537b0f2a609aeb34b85160d4d510979c

**Comment by xeipuuv** [comment]
I see, sounds good, i can merge it to the main repo.

**Comment by cristiangraz** [comment]
You can use custom format checkers (recently added) as long as you are checking strings.

Untested example:
```go
type PalindromeFormatChecker struct {}

func (f PalindromeFormatChecker) IsFormat(input string) bool {
    s = strings.ToLower(s)
    r := []rune(s)
	for i, j := 0, len(r)-1; i < len(r)/2; i, j = i+1, j-1 {
		r[i], r[j] = r[j], r[i]
	}

	return string(r) == s
}

gojsonschema.FormatCheckers.Add("palindrome", PalindromeFormatChecker{})
```

Then in your json schema:
```json
{"type": "string", "format": "palindrome"}
```

Not sure this will meet all your use cases, but figured it would be helpful to share here since this was added not too long ago and may also be helpful to others.

**Comment by cristiangraz** [comment]
@prettymuchbryce @xeipuuv Can this be closed?

**Comment by buger** [comment]
Here is example on how `ruby-json-schema` allow extending schema: https://github.com/ruby-json-schema/json-schema#extending-schemas

It would be really great to have something similar.
