### ISSUE TITLE
Message key constants associated with error messages

### ISSUE THREAD

**Issue by nicholasf** [xeipuuv/gojsonschema#53]
Hi,

Great work on this library.

Right now validation messages are tied to a particular English representation ready for printf in locales.go-  e.g. https://github.com/xeipuuv/gojsonschema/blob/master/locales.go#L43 .

We are building an app that would like to use your library but we need messages that can be handcrafted and, eventually, internationalised.

We'd like to be able to associate constant key names with a validation message (as in i18n). I think the easiest way to do this would be to add a MessageKey to the ErrorResult object, which would map to a constant associated with the error. This would make it easy for people to build their own validation messages if they wanted, mapping them to the MessageKey.

I'll fork and add this and make a PR. I just wanted to check first in case if you'd already thought about this and had another solution.

Cheers,
Nicholas

**Comment by nicholasf** [comment]
See https://github.com/xeipuuv/gojsonschema/pull/54

**Comment by xeipuuv** [comment]
Hi,
I just merged christiangraz's pull request that would solve this issue.
see https://github.com/xeipuuv/gojsonschema/issues/51.

**Comment by nicholasf** [comment]
That's fine. I didn't see it when I began my solution. If it supplies error codes we can use those.
