### ISSUE TITLE
Embeding json schema

### ISSUE THREAD

**Issue by sebest** [xeipuuv/gojsonschema#56]
Hello,

Do you think it would be possible to embed the json schema in the code.

For example generating a .go file containing the json schema as a struct, something similar to that: https://github.com/pquerna/ffjson#using-ffjson-with-go-generate

this way the go binary would remain self sufficient.

thanx

**Comment by xeipuuv** [comment]
Hi, 
You could use a StringLoader to embed your schema in your source code.
see https://github.com/xeipuuv/gojsonschema#loaders

**Comment by sebest** [comment]
Hello,

I want to store the file as json in my repository and use $ref to factorize the schema and also be able to reference the schema in my swagger specification.

But when i build my app i want to have it build in the binary.

I hope this clarify the usecase?

**Comment by xeipuuv** [comment]
About swagger specification there is a feature being actually discussed, but it is not yet available. 
(see https://github.com/xeipuuv/gojsonschema/pull/55).

Now, to be able to use $ref you need a proper file's URI (http or file scheme), and there is no way (yet) to "ref" to a go variable.

What you could do though, is create a temporary JSON file when you program starts and ref it using the file URI scheme.

**Comment by sebest** [comment]
The $ref was the main issue otherwise i could have used something like go-bindata to embed the schema.

The solution i was thinking about was to resolve all $ref during the build and generate a Go struct per schema and store it in a temporary .go file that i could compile inside my code.

From there i could simply use the NewGoLoader as the schema would be a go struct with no more $ref as they would have been all resolved.

Question: the $ref are resolved when we call loadSchema() or each time we validate() the JSON?

**Comment by xeipuuv** [comment]
$refs are resolved when loadSchema() is called.
If i understand correctly your solution is actually "flattening" your schemas so that your "refs" are embedded (using "$ref": "#/definitions/sub_schema"), i guess this would work and do what you are expecting.

**Comment by sebest** [comment]
Doing some quick tests it seems that the schema file are read from disk each time i call gojsonschema.Validate(schemaLoader, documentLoader)

I would expect them them to be 'cached' as i don't see how it can scale if i use it to validate input from a JSON API where i would have to validate every requests.

**Comment by xeipuuv** [comment]
https://github.com/xeipuuv/gojsonschema#validation
