### ISSUE TITLE
File URL not handled correctly on Windows

### ISSUE THREAD

**Issue by dgolub** [xeipuuv/gojsonschema#61]
The library doesn't properly handle loading a JSON schema from a properly formed file URL when running on Windows.  There, a file URL will have an extra slash after the `file://` and the path with have slashes converted to backslashes and spaces escaped.  Extra logic is needed to handle these conversions at jsonLoader.go:78-82.

**Comment by amolmanwar** [comment]
I observed the same Issue with the below Error.
%!s(bool=false) %!s(bool=true) %!s(bool=false) %!s(bool=true) %!s(bool=false)} must be canonical.

Any information if anyone actively contributing on this issue?

Thanks in advance.
