### ISSUE TITLE
Generate Go Structs From Schema

### ISSUE THREAD

**Issue by saulshanabrook** [xeipuuv/gojsonschema#64]
I want to be able to **verify** and then **access* the data from a JSON document, based on its schema. 

It seems like this library solves the first problem, but do you know how to achieve the second? I could manually create a bunch of Go structs for the schema, but is there a better way? Like a way to generate Go types based on the schema?

**Comment by xeipuuv** [comment]
If I understand correctly, you basically want to access/read the unmarshalled JSON document that was previously loaded during the validation process to do your own stuff.

Now, that is actually pretty funny nobody noticed that before, 
and i wonder how the library users do handle that.

Maybe they "pre-load" the JSON into the Struct or String versions of loaders... but indeed, it would be way better if the library handled that in a convenient manner.

A correct way to handle that would be to do some little work on the JSONLoader (jsonLoader.go file) interface. Internally, these loaders use the unmarshalled document but they do not provide any public access to it.

That way, we could do something like that:

```
result, err := gojsonschema.Validate(schemaLoader, documentLoader)
// handle error if any...

document := documentLoader.Document()
```

**Comment by saulshanabrook** [comment]
@xeipuuv I think we are talking about the same thing. Basically I want to turn all my big string of JSON into a big Go type structures, with structs and slices.

Currently I can do this by defining this manually and then unmarshalling into this type, but since the JSON schema holds a bunch of type information, it seems like it would make sense to be able to generate these Go types from the JSON schema.

Does that make any sense?

**Comment by xeipuuv** [comment]
I see, so you want to generate from the schema, and not access the unmarshalled document to validate.
Well, gojsonschema do not offer this feature and this is actually one big piece of work :)

**Comment by saulshanabrook** [comment]
Yeah thats what I thought. Well I don't plan on tackling it right now, but it seems like it would be nice to have.

**Comment by snikch** [comment]
You may be interested in this https://github.com/snikch/schematype

It requires the files to be generated before use, so it's not dynamic, but afaik that's pretty much impossible without ending up with the ugliest of code, and you'd lose all type safety, and have to update your expectations when the schema changed anyway.

Keen for feedback, not everything is implemented yet, but for basic types it should work.

**Comment by saulshanabrook** [comment]
@snikch Looks pretty interesting

**Comment by gedw99** [comment]
I also need the same btw
