### ISSUE TITLE
Can I generate a Schema?

### ISSUE THREAD

**Issue by xogeny** [xeipuuv/gojsonschema#66]
I see that this library can load a schema (seemingly from different sources, strings, Go types?, etc).

But once that schema is loaded, is there a way to output it back out as a JSON Schema?  I'm curious because it would be nice to see what the library is actually using internally (after any normalization it might perform).

If I understand the API, it seems as though the library is able to build a schema from an existing Go type.  In that case, it would be even more interesting to be able to output the resulting schema.

Or am I missing something?

**Comment by xeipuuv** [comment]
The library doesn't implement that feature.

Now, if this feature existed, and if that feature was written properly, 
i guess it would have to output exactly what you did feed him beforehand.

Internally, the library do things like pooling the references, storing various informations help validation and provide interesting errors messages, but still, this is not part of the JSON schema but more of temporary storage to do the job.

There are similar topics there https://github.com/xeipuuv/gojsonschema/issues/64 and there https://github.com/xeipuuv/gojsonschema/issues/15 that may be what you are looking for.
