### ISSUE TITLE
Validation failed.

### ISSUE THREAD

**Issue by wizard580** [xeipuuv/gojsonschema#69]
We have valid json which valid against schema. 
http://www.jsonschemavalidator.net/  shows that validation OK, but "gojsonschema" failed.

Json:

{"id":8021929379916255508,"version":14,"ppid":"001N","event_type":108,"event_name":"GAME1","time":1438387197195,"date":"2015.07.31 23:59:57:195","uid":2876123,"sid":217821637863217869,"seq":3828,"conn":"38ge62g6g26gd6g23eg676d2","accounts":{"1":{"balance":567748580,"available":521648580,"children":{"111005166":{"balance":36600000,"amount":-1000000},"111012365":{"balance":9500000}}},"2":{"balance":59}},"server":111,"server_state":"ALIVE","buildno":"2.9.16","params":{"login":"login","nick":"nick","desk":{"id":111005166,"game":"GAME1","hand":16094218,"gip":false,"dealer_place":0,"places":[{"place":1,"reserved":false,"player":46966470,"amount":36600000,"stake":1000000,"fold":false},{"place":3,"reserved":false,"player":17898625,"amount":9000000,"stake":0,"fold":false},{"place":5,"reserved":false,"player":58429925,"amount":0,"stake":0,"fold":false},{"place":7,"reserved":false,"player":23778346,"amount":9000000,"stake":0,"fold":false},{"place":9,"reserved":false,"player":54497914,"amount":44000000,"stake":500000,"fold":false}],"category":500000,"zone":"C0","type":"STANDARD","level":0,"limit":"NL","speed":"FAST","placesCount":5,"vip":false,"pot":0},"type":"BIG_BLIND","amount":1000000}}

Schema:
https://gist.github.com/wizard580/ec6e7c859296b53a9df3

**Comment by xeipuuv** [comment]
What are the validation error messages ?

**Comment by wizard580** [comment]
The document is not valid. see errors :
- (root): Must validate one and only one schema (oneOf)
- event_type: event_type must be one of the following: 100
- place: place is required
- id: Invalid type. Expected: integer, given: integer
- sid: Invalid type. Expected: integer, given: integer

I think you can test it. Just use example in your docs.

**Comment by xeipuuv** [comment]
gojsonschema uses ECMA MAX_SAFE_INTEGER (9007199254740991) and MIN_SAFE_INTEGER(-9007199254740991) to validate the minimum and maximum allowed values of an integer.

Both "id" and "sid" are expected to be integers, but their values are too big, resulting in errors.

**Comment by wizard580** [comment]
Can it be increased? It's important, other libs supports this.

**Comment by wizard580** [comment]
int64 max = 18446744073709600000
so, 9007199254740991 - too small

**Comment by xeipuuv** [comment]
Could be, we just need to put some thoughts on it.

**Comment by wizard580** [comment]
I've made dirty hack for issue (for float64 to int64)
But still get error: 
- (root): Must validate one and only one schema (oneOf)

I think it's completly different issue

**Comment by xeipuuv** [comment]
The integer boundaries is definitely one issue.
I tried with your document and schema, with smaller "id" and "sid", and it validates.

**Comment by xeipuuv** [comment]
I also tried my own dirty hack, 
I edited https://github.com/xeipuuv/gojsonschema/blob/master/utils.go#L64-L78 and removed the following checks :

  || f < min_json_float || f > max_json_float"

The validation passes with your original document and schema.

**Comment by wizard580** [comment]
Strange. I've set very short id and sid and it's still show error
(root): Must validate one and only one schema (oneOf)

Now I'll test your patch... yes, it validates. I think it will lost id and sid values, but it ok.

**Comment by wizard580** [comment]
Will you make a good patch for this issue? Sure I'm not alone

**Comment by xeipuuv** [comment]
I will think about it and see what needs to be done when I have some free time.

**Comment by wizard580** [comment]
I've found one more issue:
same schema, different json with "event_type: 1", now I see errors:
- params.lat: Must not validate the schema (not)
- params.lon: Must not validate the schema (not)

You can search schema for this part.
"lat":{  "type":"number", "not":{ "type":"integer" }}
"lon":{"type":"number","not":{ "type":"integer" }}

**Comment by wizard580** [comment]
If you you'll give me your private email I'll show full json string that failed.

**Comment by xeipuuv** [comment]
what are the values of "lat" and "lon" ? and what version of gojsonschema are you using ? patched one ?

**Comment by wizard580** [comment]
lat and lon == 0.0 (numeric, not integer)
sure, without "|| f < min_json_float || f > max_json_float"

**Comment by xeipuuv** [comment]
I have the found the issues, i will include these in a future path.

**Comment by wizard580** [comment]
Please... It's the best Go json validator, but this issue blocks my work. Can you say when I should expect fix? I can test patch for you :)

**Comment by xeipuuv** [comment]
I have honestly no idea, it requires a good amount of work and tests; 
Also, i dont have a lot of free time these days.

The first patch seems to solve your first issue, 
and as a temporary solution you can disable from your schema:

``
"not":{ "type":"integer" }
``

**Comment by wizard580** [comment]
Alter schema - impossible. It's from other system and I can't control it. I need to make it work with this schema and with a huge count of jsons.

**Comment by xeipuuv** [comment]
I created a new branch https://github.com/xeipuuv/gojsonschema/tree/json.Number that seems to solve the issues, this is a work in progress and requires more cleanup and testing before going to the master branch. Let me know if that works on your side.

**Comment by wizard580** [comment]
yes!
this validates! Now I'll test validation of all my jsons. 
Thanks!

**Comment by wizard580** [comment]
Another failures:
{"id":7447063907,"version":14,"ppid":"001N","event_type":137,"event_name":"EVENTNAME","time":1438387198553,"date":"2015.07.31 23:59:58:553","uid":4366263,"sid":256165381,"seq":1,"conn":"eacd88a1889e70ff4eb8efff395f","accounts":{},"server":103,"server_state":"ALIVE","buildno":"2.9.5","params":{"login":"100002","nick":"mynickname","fb":{"fbId":20010026588,"first_name":"Fn","last_name":"LName","gender":"male","locale":"en_US","name":"Fn LName","age_min":21,"link":"http://mylink.com","timezone":8,"updated_time":1433917742000,"verified":true}}}

Errors:
- (root): Must validate one and only one schema (oneOf)
- event_type: event_type must be one of the following: 229
- 1: 1 is required

**Comment by xeipuuv** [comment]
Fixed in master branch
