### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by wizard580** [xeipuuv/gojsonschema#71]
Were there any performance tests?
I see slow validations, so I try to look inside and figure out what happens.

May be devs knows where to look first?

**Comment by xeipuuv** [comment]
Performance depends on many factors. How do you load your documents and schema ? 
how do you perform the validations ? what kind of loaders you are using ? etc...
Showing some code would help.

**Comment by wizard580** [comment]
First of all: Validated 1000 jsons in 1.53061351s (may be I'm wrong and it's good result). It result for failed json, but I can test for passed too.

short example:
dataSchema,_ = jsonschema.NewSchema( jsonschema.NewReferenceLoader("file://"+ *dataSchemaFile) )
for {
    dat := jsonschema.NewStringLoader("some long json string")
    res,_ := dataSchema.Validate(dat)
}

**Comment by xeipuuv** [comment]
So that's 1.5 ms for each JSON. Is that too slow ?

**Comment by wizard580** [comment]
I look at https://github.com/ebdrup/json-schema-benchmark
current validation little better than "jsck"

**Comment by xeipuuv** [comment]
There is always room for improvement and i guess it also depends a lot on the input document and schema.

**Comment by wizard580** [comment]
Yes, I know.
So I try to dig in look what places can be improved and ask a for a place where I can look first. Or just do as I can.

**Comment by xeipuuv** [comment]
Then its better to use go profiling tools, it will give you real results without having to look for yourself.

**Comment by wizard580** [comment]
Oh, yes. I'm not profi at Go, so don't remember all tools.
Thanks for hint.
