### ISSUE TITLE
maximum validation error is incorrect

### ISSUE THREAD

**Issue by Loster83** [xeipuuv/gojsonschema#81]
When maximum validation is applied I am getting the wrong error 'desc: Must be less than %max%'
Seems like the 'max' should be used instead of 'min' in validation.go:
https://github.com/xeipuuv/gojsonschema/blob/master/validation.go#L783
https://github.com/xeipuuv/gojsonschema/blob/master/validation.go#L794
Looking at the locales - the %max% (not %min%) is used there:
https://github.com/xeipuuv/gojsonschema/blob/master/locales.go#L186

The same is for min (should be 'min' instead of 'max'):
https://github.com/xeipuuv/gojsonschema/blob/master/validation.go#L810
https://github.com/xeipuuv/gojsonschema/blob/master/validation.go#L821

**Comment by lylex** [comment]
Should be OK now.

**Comment by xeipuuv** [comment]
see https://github.com/xeipuuv/gojsonschema/pull/85
