### ISSUE TITLE
Bad error message when have exclusiveMaximum or exclusiveMinimum

### ISSUE THREAD

**Issue by lylex** [xeipuuv/gojsonschema#86]
When have such schema:

                "x":{
                    "type":"number",
                    "minimum": 0,
                    "exclusiveMinimum": true
                }

And then validate json like "x:0", the error message is something like "x: Must be greater than or equal to 0", the error should be like "x: Must be greater than 0".

exclusiveMaximum is the same error.

**Comment by lylex** [comment]
As documented in http://json-schema.org/latest/json-schema-validation.html#anchor21

If exclusiveMinimum is absent, that equals to "exclusiveMinimum: false", so we need to correct some GT, GTE, LT and LTE bug.

**Comment by cristiangraz** [comment]
@lylex Did this commit fix this, or is this bug still pending? Wonderinf if this issue can be closed. https://github.com/xeipuuv/gojsonschema/commit/8a23b3506e673c5f92cc5e4aff27502ae0cced89

I ran your example and see the "must be greater than 0" error now.

**Comment by lylex** [comment]
I think it is already fixed, so I closed it.
